---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.mariadb.com
  resources:
  - databases
  - grants
  - mariadbs
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenchs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenchs/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenchs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappesites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappesites/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappesites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkpaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkpaces/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkpaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - sitebackups/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitebackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboardcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboardcharts/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboardcharts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboards/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitedashboards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - sitejobs/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - sitejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - siteusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - siteusers/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - siteusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - siteworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vyogo.tech
  resources:
  - siteworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - vyogo.tech
  resources:
  - siteworkspaces/status
  verbs:
  - get
  - patch
  - update
