---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
# Core resources
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Apps resources
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Batch resources
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Networking resources
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Storage classes (read-only access)
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
# Frappe CRDs - Core resources
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches
  - frappesites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Frappe CRDs - Finalizers
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches/finalizers
  - frappesites/finalizers
  verbs:
  - update
# Frappe CRDs - Status subresource
- apiGroups:
  - vyogo.tech
  resources:
  - frappebenches/status
  - frappesites/status
  verbs:
  - get
  - patch
  - update
# Extended Frappe CRDs - Additional resources
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkspaces
  - sitebackups
  - sitedashboardcharts
  - sitedashboards
  - sitejobs
  - siteusers
  - siteworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Extended Frappe CRDs - Finalizers
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkspaces/finalizers
  - sitebackups/finalizers
  - sitedashboardcharts/finalizers
  - sitedashboards/finalizers
  - sitejobs/finalizers
  - siteusers/finalizers
  - siteworkspaces/finalizers
  verbs:
  - update
# Extended Frappe CRDs - Status subresource
- apiGroups:
  - vyogo.tech
  resources:
  - frappeworkspaces/status
  - sitebackups/status
  - sitedashboardcharts/status
  - sitedashboards/status
  - sitejobs/status
  - siteusers/status
  - siteworkspaces/status
  verbs:
  - get
  - patch
  - update
